# Generated by Django 4.2.5 on 2023-10-22 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visitors',
            options={},
        ),
    ]
