# Generated by Django 4.2.5 on 2023-10-02 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_historicaluser_deleted_at_user_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='username',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
