# Generated by Django 4.2.5 on 2023-10-23 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_historicaluser_username_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
