# Generated by Django 4.2.7 on 2023-12-03 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_historicaluser_city_user_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.DeleteModel(
            name='HistoricalUser',
        ),
    ]
