# Generated by Django 4.2.7 on 2023-12-03 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_user_username_delete_historicaluser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='document',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
