version: '3.9'

services:
  frontend:
    build: ../sistemas_inteligentes_frontend
    env_file:
      - ../sistemas_inteligentes_frontend/.env.local
    depends_on:
      - backend
    command: yarn start

  backend:
    build:
      context: .
      dockerfile: docker/dev.Dockerfile
    env_file:
      - .env
    environment:
      - DB_HOST=db
    volumes:
      - ./src:/src
    command: >
      sh -c "python manage.py wait_for_db && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db
    restart: on-failure

  db:
    image: postgres
    env_file:
      - .env
    volumes:
      - ./database:/var/lib/postgresql/data
    ports:
      - 5432:5432

  nginx:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend

volumes:
  database:
