version: '3.9'

services:
  frontend:
    build: ../sistemas_inteligentes_frontend
    ports:
      - 3000:3000
    env_file:
      - ../sistemas_inteligentes_frontend/.env.local
    depends_on:
      - backend
    command: yarn start

  backend:
    build:
      context: .
      dockerfile: docker/dev.Dockerfile
    env_file:
      - .env
    environment:
      - DB_HOST=db
    ports:
      - "8000:8000"
    volumes:
      - ./src:/src
    command: >
      sh -c "python manage.py wait_for_db && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db
    restart: on-failure

  db:
    image: postgres
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - ./database:/var/lib/postgresql/data

volumes:
  database:
