# Generated by Django 4.2.13 on 2024-06-17 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MachineInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('rod_set', models.DecimalField(decimal_places=2, max_digits=10)),
                ('flow_pump', models.DecimalField(decimal_places=2, max_digits=10)),
                ('time_start', models.DateTimeField()),
                ('time_on', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'machine_info',
            },
        ),
        migrations.CreateModel(
            name='NodesInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('temperature_rod', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('temperature_environment', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('humidity_environment', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('concentration_c2h4', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('concentration_ozone', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('info_extra', models.JSONField(null=True)),
                ('id_node', models.CharField(max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ripener.machineinfo')),
            ],
            options={
                'db_table': 'nodes_info',
            },
        ),
    ]
