# Generated by Django 4.2.5 on 2023-10-01 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodesstorage',
            name='altitude',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='nodesstorage',
            name='humidity',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='nodesstorage',
            name='pressure',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='nodesstorage',
            name='temperature',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
