# Generated by Django 4.2.7 on 2024-06-09 20:27

from django.db import migrations
from nodes.models import NodesStorage, Nodes


def remove_duplicates(apps, schema_editor):
    for node in Nodes.objects.all():
        # Get all the records for the current node
        records = list(NodesStorage.objects.filter(node=node).order_by('date_time', '-created_at'))
        for i in range(len(records) - 1):
            # If the current record and the next one have the same date_time, remove the current one
            if records[i].date_time == records[i + 1].date_time:
                records[i].delete()


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0003_weatherstation'),
    ]

    operations = [
        migrations.RunPython(remove_duplicates),
    ]
